proposal: Add logging standard
zupit-it/zupit-standards pull request #8
Opened 2022-12-06 15:21 UTC by alessandro-mariotti-zupit

Closes #6

2023-03-06 15:32 UTC, alessandro-mariotti-zupit commented on common/logging.md
> +# Applications Logging
Created Issue for improving this https://github.com/zupit-it/zupit-standards/issues/17

2023-03-06 15:32 UTC, alessandro-mariotti-zupit commented on common/logging.md
> +## Code for Logging
Created issue for improving this: https://github.com/zupit-it/zupit-standards/issues/18

2023-03-09 10:22 UTC, omar-muscatello-zupit commented on common/logging.md
> + `- api
Why are this backticks needed?

2023-03-09 10:22 UTC, omar-muscatello-zupit commented on common/logging.md
> +- Logged user *(Where available)*
Is it referring to the user id? is it safe to log it?

2023-03-09 10:25 UTC, omar-muscatello-zupit commented on common/logging.md
> +There could be some exceptions on this, based on customer's requirements or project constraints, where we fallback on ad-hoc solutions or classic logfiles (see the next sections for details)
`logfiles` typo?

2023-03-09 10:30 UTC, omar-muscatello-zupit commented on common/logging.md
> +- Every Endpoint/API must log it's request body (if any) with **DEBUG LEVEL**
I don't think this is safe. For example, when calling the authentication endpoint, the request body would include user credentials (e.g. OAuth Resource Owner Flow).

We should also consider GDPR compliance: request body could include user information (SaveProfile API).

This comment is not valid if we should have different log levels for each environment. For example:
- Testing -> DEBUG: even if we log user credentials, those are testing credentials

What do you think?

2023-03-17 12:42 UTC, alessandro-mariotti-zupit commented on common/logging.md
> + `- api
Because it's a directory tree structure and  I like how it looks

2023-03-17 13:11 UTC, pietro-devigili-zupit requested changes

2023-03-17 13:11 UTC, pietro-devigili-zupit commented on common/logging.md
> +
Add Omar to list?

2023-03-20 11:41 UTC, pietro-devigili-zupit approved these changes

2023-03-20 11:42 UTC, pietro-devigili-zupit approved these changes

2023-03-20 11:54 UTC, omar-muscatello-zupit approved these changes

2023-03-20 11:55 UTC, alessandro-saiani-zupit approved these changes

2023-03-20 11:59 UTC, merged